name=ESP-FLY-BLIMP-WITH-CAM
version=1.0.0
author=User
maintainer=User
sentence=ESP-FLY Blimp With Internal Vision / IMU Based Guidance
paragraph=Simple blimp utilizing the Xiao ESP32-S3, ESP-Fly motor driver / IMU board, and OV-series camera for control. Can be flown both manually or autonomously.
category=Sensors
url=https://github.com
architectures=esp32
includes=Vision.h,IMU.h